# Generated by Django 6.0.1 on 2026-02-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('is_cloud_based', models.BooleanField(default=False)),
            ],
        ),
    ]
